- source/dustSystem.js
- source/gameCamera.js
- source/lights.js
Quick change fixes an issue with how events are setup on the camera/dust/lights @BrettASwift
> Application State Event Fix

- index.vwf.config.yaml
- index.vwf.html
- index.vwf.yaml
- minimal_jplayer_style.css
- source/scenario/scenario3f.vwf.yaml
- source/view/index.js
- source/view/videoController.js
jPlayer is now integrated with the Application State branch
> Application state jplayer integration

- source/scenario/introScreenScenario.vwf.yaml
- source/scenario/scenario1i.vwf.yaml
- source/scenario/scenario3f.vwf.yaml
- source/scene.js
- source/view/index.js
- source/view/videoController.js
jPlayer supports WebM and h264 now. This PR depends on [PR 477](  https://github.com/virtual-world-framework/vwf/pull/477 )
> Multi format support

- source/triggers/clauses/clauseProto_OnEvent.js
- source/triggers/groups/triggerGroup.js
Small update to use random and time properties provided by VWF for replication safety @kadst43
> Use VWF Date and Time 

- source/view/index.js
@nmarshak1337 
Along with the other changes I've made to the app and the Blockly drivers, this change fixes the gray-out by firing a change event on the workspace which internally updates the toolbox.
Requires: https://github.com/virtual-world-framework/vwf/pull/481
> Update Max Blocks (RAM Gray-out Fix)

- source/hud/cameraSelector.js
This should fix the `camera_thirdPerson.png` bug on the Illinois server.
> Fix image case

- source/scenario/blockly/scenario_dummy.xml
- source/view/blocks.js
> Blockly Check and Solve

- heightmap_generator/three.js
- source/triggers/clauses/clauseProto_OnEvent.js
- source/triggers/groups/triggerGroup.js
Reinstated the slower trigger updates and made a change to using vwf time in one location. @kadst43
> Small improvements to execution framerate

- source/cameraMount.js
- source/cameraTarget.js
- source/cameraTarget.vwf.yaml
- source/gameCamera.js
- source/gameCamera.vwf.yaml
- source/rover.js
- source/scene.js
- source/view/index.js
- Camera no longer snaps multiple times when changing view
- Camera no longer gets offset when switching from top down to another mode
- Camera now stays in the same camera view when switching between rovers
- Camera now properly stops following a target after being switched off of that target
> Camera work

- source/hud/roverSelector.js
- source/rover.vwf.yaml
- source/scene.js
Fixed a few undefined errors in synchronization and rounded the battery count for the secondary rovers.
@kadst43 @AmbientOSX @nmarshak1337
> Misc improvements

- index.vwf.html
- index.vwf.yaml
- source/timer.js
- source/timer.vwf.yaml
- source/view/index.css
- source/view/index.js
Here's the timer for the competition. It times each scenario individually and the aggregate time.
> Scenario Timer

- index.vwf.html
- index.vwf.yaml
- source/scene.js
- source/timer.js
- source/timer.vwf.yaml
- source/view/index.css
- source/view/index.js
@kadst43 @AmbientOSX @nmarshak1337
> Add timer to mars-game-development

- index.vwf.html
- source/scenario/blockly/graph.xml
- source/scenario/blockly/graph2a.xml
- source/scenario/blockly/graph2b.xml
- source/scenario/blockly/graph2c.xml
- source/scenario/blockly/graph2d.xml
- source/scenario/blockly/graph2e.xml
- source/scenario/blockly/graph2f.xml
- source/scenario/blockly/graph3a.xml
- source/scenario/blockly/graph3b.xml
- source/scenario/blockly/graph_dummy.xml
- source/scenario/blockly/scenario1.xml
- source/scenario/blockly/scenario1b.xml
- source/scenario/blockly/scenario1c.xml
- source/scenario/blockly/scenario1d.xml
- source/scenario/blockly/scenario1e.xml
- source/scenario/blockly/scenario1f.xml
- source/scenario/blockly/scenario1g.xml
- source/scenario/blockly/scenario1h.xml
- source/scenario/blockly/scenario2f.xml
- source/scenario/blockly/scenario3a.xml
- source/scenario/blockly/scenario3b.xml
- source/scenario/blockly/scenario3c.xml
- source/scenario/blockly/scenario3d.xml
- source/scenario/blockly/scenario3e.xml
- source/scenario/blockly/scenario_dummy.xml
- source/view/blocklyUI.js
- source/view/blocks.js
- source/view/index.css
- source/view/index.js
@kadst43 @BrettASwift @nmarshak1337 Adds categories, modifies a bunch of blocks connection code, adds others, demonstrates collapsing blocks, cleans out some unused old Block code, and fixes scrolling issues with Blockly UI changes.
Depends on: https://github.com/virtual-world-framework/vwf/pull/486
> More Blockly Added Capability

- source/rover.js
- source/scenario/blockly/scenario_dummy.xml
- source/scenario/blockly/scenario_dummy_perry.xml
- source/scenario/scenario_dummy.vwf.yaml
- source/scene.js
- source/view/blocks.js
- source/view/index.js
@kadst43 @BrettASwift @nmarshak1337 
Depends on https://github.com/virtual-world-framework/vwf/pull/488
This is a work in progress since we're still figuring out collision handling. Should generally not be used in conjunction with other movement blocks for demo purposes.
> Blockly Radial Move & Blockly args fix

- index.vwf.yaml
- source/pickups/signal.vwf.yaml
- source/rover.js
- source/rover.vwf.yaml
- source/scenario/blockly/scenario1g.xml
- source/scenario/blockly/scenario1h.xml
- source/scenario/blockly/scenario2f.xml
- source/scenario/blockly/scenario3a.xml
- source/scenario/blockly/scenario3b.xml
- source/scenario/blockly/scenario3c.xml
- source/scenario/blockly/scenario3d.xml
- source/scenario/blockly/scenario3e.xml
- source/scenario/blockly/scenario_dummy.xml
- source/scenario/scenario_dummy.vwf.yaml
- source/view/blocks.js
- source/view/index.js
@kadst43 Also made some various changes to arithmetic blocks and number blocks that I assumed we'd want.
> Blockly Signal Block

- source/rover.js
- source/scenario/blockly/scenario_dummy_perry.xml
- source/scene.js
- source/view/blocklyUI.js
- source/view/blocks.js
- source/view/index.js
> Blockly multi tracing and looping

- source/marsGameSound.vwf.yaml
- source/scenario/globalScenarioTriggers.vwf.yaml
- source/scene.js
- source/triggers/clauses/clause_OnBlocklyBlock.js
- source/triggers/clauses/clause_OnBlocklyBlock.vwf.yaml
- source/triggers/generators/generator_Clause.vwf.yaml
- source/view/blocks.js
- source/view/index.js
@kadst43 I cant figure out why the new OnBlocklyBlock trigger is getting ignored. Necessary to determine when a rover is idling. Everything else should be all set. Rovers are playing their own sounds.
> OnBlocklyBlock - Rover Sounds - Exe Small Fix

- source/shaders/animatedShader.vwf.yaml
- source/shaders/mixMap.vwf.yaml
- source/shaders/projectedGrid.vwf.yaml
- source/shaders/texturedShader.vwf.yaml
Fixed a couple of bugs and added the complete shader code for lights and shadows from threejs to all of our current custom shaders.
> Shader fixes

- source/rover.js
- source/rover.vwf.yaml
- source/scenario/blockly/scenario_dummy.xml
- source/scenario/blockly/scenario_dummy_perry.xml
- source/scenario/scenario_dummy.vwf.yaml
- source/triggers/clauses/clause_OnBlocklyPolygon.js
- source/triggers/clauses/clause_OnBlocklyPolygon.vwf.yaml
- source/view/blocks.js
- source/view/index.js
@kadst43 Accounts for forward and reverse cyclical permutations and allows a user to start at any point in the polygon.
> Polygon Trigger Generalization

- source/scenario/blockly/scenario_dummy.xml
- source/view/blocks.js
> Quick changes to block order and visual style

- index.vwf.yaml
- source/mainMenu.vwf.yaml
- source/shaders/animatedShader.vwf.yaml
- source/shaders/mixMap.vwf.yaml
- source/shaders/projectedGrid.vwf.yaml
- source/shaders/scaledTextureShader.vwf.yaml
- source/shaders/texturedShader.vwf.yaml
This has the triangle stuff and some other shader improvements. The grid is fully functional now with axis lines and all, whether or not we use it at this point.
> Triangle outline

- index.vwf.yaml
- source/scene.js
- source/shaders/mixMap.vwf.yaml
@kadst43 
Added the `drawSchematicTriangle` function to the scene. You can hook up to that in your trigger action.
> Added function to scene to draw the triangle

- source/hud/roverSelector.js
- source/rover.js
- source/rover.vwf.yaml
- source/scenario/blockly/mission3.xml
- source/scenario/blockly/mission4.xml
- source/scenario/blockly/scenario3a.xml
- source/scenario/blockly/scenario3b.xml
- source/scenario/blockly/scenario3c.xml
- source/scenario/blockly/scenario3d.xml
- source/scenario/blockly/scenario3e.xml
- source/scenario/blockly/scenario_dummy.xml
- source/scenario/blockly/scenario_dummy_perry.xml
- source/scenario/mission3task1.vwf.yaml
- source/scenario/scenario3a.vwf.yaml
- source/scenario/scenario3c.vwf.yaml
- source/scenario/scenario3e.vwf.yaml
- source/scenario/scenario_dummy.vwf.yaml
- source/view/blocklyUI.js
- source/view/blocks.js
- source/view/index.js
> RAM -> Blocks Remaining && Anomaly -> Metal

- source/scenario/mission3task1.vwf.yaml
- source/scenario/mission4task1.vwf.yaml
- source/scenario/mission4task2.vwf.yaml
- source/scenario/mission4task3.vwf.yaml
- source/scenario/mission4task4.vwf.yaml
- source/scenario/mission4task5.vwf.yaml
- source/scenario/mission4task6.vwf.yaml
- source/triggers/clauses/clause_OnBlocklyPolygon.js
- source/triggers/clauses/clause_OnBlocklyPolygonFailed.js
- source/view/index.js
@kadst43 @BrettASwift If we succeed after drawing a polygon be sure to stop blockly execution and clear blockly to facilitate loading of the next task's blockly XML.
Requires: https://github.com/virtual-world-framework/vwf/pull/498
> Failure fix

- source/marsGameSound.vwf.yaml
> VO Replaces Now M3+

- source/marsGameSound.js
- source/marsGameSound.vwf.yaml
- source/view/blocks.js
@kadst43 ...snuck a few spell check/VO syntax error fixes in as well.
> Perry Portrait and Heading Change

- index.vwf.yaml
- source/scene.js
- source/view/index.js
- source/view/missionBriefs.js
@kadst43 
This will give you a method on the scene to tie to an action and an event when the user clicks the close button.
> Add method for opening the mission brief & rewrite briefs.

- source/scenario/blockly/mission4_perry.xml
- source/scenario/mission3task1.vwf.yaml
- source/scenario/mission4task1.vwf.yaml
- source/triggers/clauses/clause_Delay.js
Also makes the mission brief open after the dialog for 3-1 and 4-1.  I'm using a delay, which is the wrong
way... but I'll debug the soundFinished event next.
> Makes the delay clause actually do something!

- source/rover.js
- source/rover.vwf.yaml
- source/scenario/blockly/mission3.xml
- source/scenario/globalScenarioTriggers.vwf.yaml
- source/scenario/mission3task1.vwf.yaml
- source/scenario/mission5task1.vwf.yaml
- source/triggers/clauses/clause_OnBlocklyPolygon.js
- source/triggers/clauses/clause_OnBlocklyPolygon.vwf.yaml
- source/view/blocks.js
@kadst43 @BrettASwift Success + failure is still happening on the triangle missions but I wanted to get these other fixes in. Still not sure what is going on there.
...also quickly added a number block that lets you visually select an angle that corresponds with the angles we're using in the environment. Might help with the "showing with hands" issue described on the call. Use it or ignore it.
> Misc Fixes 5-20-15

- index.vwf.yaml
- source/scenario/blockly/graph2d.xml
- source/scenario/blockly/graph2e.xml
- source/scenario/blockly/graph2f.xml
- source/scenario/blockly/graph3a.xml
- source/scenario/blockly/graph3b.xml
- source/scenario/blockly/graph_dummy.xml
- source/scenario/blockly/scenario1g.xml
- source/scenario/blockly/scenario1h.xml
- source/scenario/blockly/scenario2f.xml
- source/scenario/blockly/scenario3a.xml
- source/scenario/blockly/scenario3b.xml
- source/scenario/blockly/scenario3c.xml
- source/scenario/blockly/scenario3d.xml
- source/scenario/blockly/scenario3e.xml
- source/view/blocklyUI.js
- source/view/index.css
- source/view/index.js
@BrettASwift I cant for the life of me figure out why Blockly resizes when the window changes size but not when I resize the blocklyWrapper. Any ideas? See line 77 of blocklyUI.js ...
> Blockly changes and fixes

- source/view/index.js
Rover, Rover2, and Rover3 have been changed to Manny, Perry, and Rosie respectively within the Blockly tabs.
> Changed the way the rover's names show up on the blockly tabs.

- source/view/index.css
Small change to opacity for readability of the tooltips and logger. Merging.
> Update logger and tooltip opacity

- source/marsGameSound.vwf.yaml
- source/scenario/blockly/mission4_perry.xml
Small changes to the blocks available to the player in Mission 4 in order to make it less confusing. Also makes a change to the opening VO which was supposed to go in with a previous branch that ultimately wasn't merged.
> Unnecessary blocks cleanup

- source/marsGameSound.vwf.yaml
- source/view/blocks.js
@kadst43 Changes the divide block, removes sensor readings (though leaves variable readings for the moment, let me know if that makes sense to change), and changes some Perry VO subtitles to [whistles]
> Blockly Block Changes & Some VO

- index.vwf.yaml
- source/rover.js
- source/rover.vwf.yaml
- source/scenario/scenario1b.vwf.yaml
- source/scene.js
- source/triggers/clauses/clause_OnBlocklyBlock.js
- source/triggers/clauses/clause_OnBlocklyPolygon.js
- source/view/blocks.js
- source/view/index.js
@jyucra @BrettASwift @kadst43 
Removes some log code that was left in as well...
> Fix onBlocklyBlock & refactor drawing block code & change block content

- source/scenario/mission4task1.vwf.yaml
- source/scenario/mission4task2.vwf.yaml
- source/scenario/mission4task3.vwf.yaml
- source/scenario/mission4task4.vwf.yaml
- source/scenario/mission4task5.vwf.yaml
- source/scenario/mission4task6.vwf.yaml
- source/scenario/scenario3c.vwf.yaml
Made some changes that were sent out in the email with a list of things to fix.
* Blockly only clears between missions where a new preset cluster has to be introduced
* Mission brief waits until VO is over.
* Fixed missing whistling noise in Mission 2
> Changes before study

- source/rover.js
@kadst43 @BrettASwift @jyucra The snap is not visibly noticeable to me so I think this works.
> Snap Rover Movement

- editor/editor.js
- source/rover.js
- source/scenario/blockly/scenario1g.xml
- source/scenario/blockly/scenario1h.xml
- source/scenario/blockly/scenario2f.xml
- source/scenario/blockly/scenario3a.xml
- source/scenario/blockly/scenario3b.xml
- source/scenario/blockly/scenario3c.xml
- source/scenario/blockly/scenario3d.xml
- source/scenario/blockly/scenario3e.xml
- source/scenario/blockly/scenario_dummy.xml
- source/scenario/blockly/scenario_dummy_perry.xml
- source/view/blocklyUI.js
- source/view/blocks.js
- source/view/index.css
- source/view/index.js
Requires https://github.com/virtual-world-framework/vwf/pull/505
@kadst43 @BrettASwift @jyucra 
All necessary changes are made and procedures can be defined in the toolbox and workspace now. Lingering issue with the toolbox div appearing that I've tried to fix with CSS multiple ways but Im thinking maybe you have a better idea @BrettASwift ?
Will continue working at the problem regardless.
> Blockly Refactor

- source/rover.js
- source/scene.js
- source/view/index.js
While we're investigating issues with setting Blockly "time between lines" making mission 4 unplayable, this circumvents the issue by not changing the execution time between blocks.
@kadst43 @BrettASwift @jyucra
> Temporary Fix for Perry

- index.vwf.yaml
> Tilemap Fix

- index.vwf.yaml
- source/naniteParticle.vwf.yaml
- source/scenario/mission4task1.vwf.yaml
- source/scenario/mission4task2.vwf.yaml
- source/scenario/mission4task3.vwf.yaml
- source/scenario/mission4task4.vwf.yaml
- source/scenario/mission4task5.vwf.yaml
- source/scenario/mission4task6.vwf.yaml
- source/scene.js
- source/triggers/actions/action_deleteNanites.js
- source/triggers/actions/action_deleteNanites.vwf.yaml
- source/triggers/generators/generator_Action.vwf.yaml
This adds the particle systems for drawing the triangles. Performance may be a concern since the particles are being handled on the CPU. Slower machines may get bogged down and we may have to reduce the particle count and rate of regeneration. However, give it a try and see what you think.
> Draw nanites

- source/scenario/globalScenarioTriggers.vwf.yaml
Temporarily commenting out the roverIdle triggers so that the rover sounds play correctly.
> Commenting out code so that the rover sounds don't immediately stop.

- source/view/blocks.js
> Dot Operator

- source/rover.vwf.yaml
- source/view/blocks.js
Position sensor changes, integer block range changed, conditional/relational attachments to posX and posY blocks.
@kadst43 @BrettASwift @jyucra
> Small Block Changes

- source/scenario/blockly/scenario1g.xml
- source/scenario/blockly/scenario1h.xml
- source/scenario/blockly/scenario2f.xml
- source/scenario/blockly/scenario3a.xml
- source/scenario/blockly/scenario3b.xml
- source/scenario/blockly/scenario3c.xml
- source/scenario/blockly/scenario3d.xml
- source/scenario/blockly/scenario3e.xml
- source/scenario/blockly/scenario_dummy.xml
- source/scenario/blockly/scenario_dummy_perry.xml
- source/view/blocklyUI.js
- source/view/index.css
- source/view/index.js
Fix trashcan visibility, fix autoclose toolbox, add in colored selection indicators as a program counter, remove IDs in predefined toolbox XML which can cause some problems.
Depends on: https://github.com/virtual-world-framework/vwf/pull/506
@kadst43 @BrettASwift @jyucra
> Core Blockly Changes Part 2

- source/scene.js
Setting the first scenario back to the start video
> Setting starting scenario back to the intro video

- source/view/blocks.js
@kadst43 We wanted this a long time ago but I was checking my todos against what is in game and it never made it in somehow so here it is.
> Splits the and/or/not block into constituent blocks

- source/scenario/mission4task6.vwf.yaml
- source/scene.js
- source/triggers/actions/action_returnToMenu.js
- source/triggers/actions/action_returnToMenu.vwf.yaml
- source/triggers/generators/generator_Action.vwf.yaml
* Adds a new action which returns you to the main menu
* Uploads new intro video and mission 1 success video
> returnToMenu and new videos

- source/scenario/blockly/mission4_perry1.xml
- source/scenario/blockly/mission4_perry2.xml
- source/scenario/blockly/mission4_perry3.xml
- source/scenario/blockly/mission4_perry4.xml
- source/scenario/blockly/mission4_perry5.xml
- source/scenario/blockly/mission4_perry6.xml
- source/scenario/mission4task1.vwf.yaml
- source/scenario/mission4task2.vwf.yaml
- source/scenario/mission4task3.vwf.yaml
- source/scenario/mission4task4.vwf.yaml
- source/scenario/mission4task5.vwf.yaml
- source/scenario/mission4task6.vwf.yaml
- source/scenario/newmission3task3.vwf.yaml
- source/view/blocks.js
* Adds limits to mission 4 (both ram and blocks wise) that forces the player to solve the scenario in the way we want them to.
* Moves blinking tile down the the rover's current position
> Changes before new players

- source/hud/blocklyButton.js
- source/hud/firstPersonButton.js
- source/hud/graphButton.js
- source/hud/missionButton.js
- source/hud/optionsButton.js
- source/hud/thirdPersonButton.js
- source/hud/tilesButton.js
- source/hud/topDownButton.js
@BrettASwift @kadst43 
This is currently in the study branch but I never PR'd for dev. Let me know if this is stylistically kosher or whether we should just set the draw to be 'onload' based from the start rather than using if/else
> Makes sure "mission critical" UI buttons always load

- source/view/index.js
> Opens the top category in Blockly by default.

- source/scenario/blockly/mission3.xml
- source/scenario/blockly/mission3b.xml
- source/scenario/blockly/mission3c.xml
- source/scenario/blockly/mission4.xml
- source/scenario/blockly/scenario3e.xml
- source/scenario/blockly/scenario_dummy.xml
- source/scenario/blockly/scenario_dummy_perry.xml
- source/view/blocklyUI.js
- source/view/blocks.js
> Split Blocks, Remove Speed Button, Disable Drag, Update Symbols

- source/view/index.css
@kadst43 
It's a little dark, but that was the best option I could find.
> Made blockly header and footer opaque

- source/view/index.js
> Restore category open/close based on scenario

- source/marsGameSound.vwf.yaml
- source/scenario/mission2task11.vwf.yaml
- source/scenario/mission2task9.vwf.yaml
- source/scenario/mission3task4.vwf.yaml
- source/scenario/temporarymission3task2.vwf.yaml
@jyucra: I tested a bit, but keep an eye on this as you test as well, please.  It should play in m2t9 if you're facing east (or south).  If it doesn't play in m2t9 then it should play in m2t11 if you're facing north (or east), but it should only play once overall.
> Make the conditional on the "this one is tricky" hint work correctly

- source/scenario/globalScenarioTriggers.vwf.yaml
> Fix the double failure bug.

- source/scenario/mission1task5.vwf.yaml
- source/scenario/mission1task7.vwf.yaml
- source/scenario/mission1task8.vwf.yaml
- source/scenario/mission2task11.vwf.yaml
- source/scenario/mission2task5.vwf.yaml
- source/scenario/mission2task6.vwf.yaml
- source/scenario/mission2task7.vwf.yaml
- source/scenario/mission2task9.vwf.yaml
- source/scenario/mission3task1.vwf.yaml
- source/scenario/mission3task2.vwf.yaml
- source/scenario/mission3task3.vwf.yaml
- source/scenario/mission3task4.vwf.yaml
- source/scenario/mission3task5.vwf.yaml
- source/scenario/mission3task6.vwf.yaml
- source/scenario/mission3task7.vwf.yaml
- source/triggers/clauses/clause_IsBlockMissing.js
- source/triggers/clauses/clause_IsBlockMissing.vwf.yaml
- source/triggers/generators/generator_Clause.vwf.yaml
* Added the recommended changes for the scenario specific failures
* Fixed the inputs for callOutObjective so it works with the recent changes
> Scenario specific failures and blinking tile fix

- index.vwf.yaml
- source/gameCamera.js
- source/roverFacingArrow.vwf.yaml
- source/scene.js
Added the rover facing arrows. I placed them under the rovers, just above the ground because the arrow was completely blocking the view of perry. Let me know what you think.
> Rover facing arrow

- source/scene.js
> Block Reset RAM fix

- source/scenario/mission2task11.vwf.yaml
- source/scenario/mission2task2.vwf.yaml
- source/scenario/mission2task5.vwf.yaml
- source/scenario/mission2task6.vwf.yaml
- source/scenario/mission2task7.vwf.yaml
- source/scenario/mission2task9.vwf.yaml
- source/scene.js
- source/triggers/actions/action_setBlocklyContext.js
- source/triggers/actions/action_setBlocklyContext.vwf.yaml
@kadst43 
Allows mutliple tabs to be enabled. I didn't do it for all scenarios, just one to test. Remember: the first node in the list will be set as the active one.
> Allow multiple blockly tabs

- index.vwf.yaml
- source/scenario/mission4task1.vwf.yaml
- source/scenario/mission4task10.vwf.yaml
- source/scenario/mission4task11.vwf.yaml
- source/scenario/mission4task12.vwf.yaml
- source/scenario/mission4task13.vwf.yaml
- source/scenario/mission4task14.vwf.yaml
- source/scenario/mission4task15.vwf.yaml
- source/scenario/mission4task2.vwf.yaml
- source/scenario/mission4task3.vwf.yaml
- source/scenario/mission4task4.vwf.yaml
- source/scenario/mission4task5.vwf.yaml
- source/scenario/mission4task6.vwf.yaml
- source/scenario/mission4task7.vwf.yaml
- source/scenario/mission4task8.vwf.yaml
- source/scenario/mission4task9.vwf.yaml
- source/scene.js
> Remove nanite particles.

- source/view/blocks.js
- source/view/index.css
- source/view/index.js
Gives visual warnings and prevents program execution for basic malformed Blockly code. Also small changes to workspace sizing.
> Blockly Warnings & Small UI Change

- source/view/blocks.js
- source/view/index.js
Addresses top block issues, trashcan show stopper and removal of variable dropdowns. Want to get these in so we can update servers before submission.
> Quick Fixes

- source/view/index.js
> Fix workspace definition error

- index.vwf.yaml
- source/buildings/marsBaseBuilding.js
- source/buildings/marsBaseBuilding.vwf.yaml
- source/buildings/solarPanel.vwf.yaml
- source/roverFacingArrow.vwf.yaml
Finally have a working hack to fix the solar panels after the "quick and easy" fixes had no effect. I wish I had a real solution or at least a real understanding of what the problem actually is, but I'm sick of this bug so it will have to suffice.
Also only showing the facing arrow in top down view consistently, removed battery from under ramp, and resized jplayer to 800x600.
Wish this PR had more meat, but the solar panel bug really ate up all of my time.
> Brett punchlist 2

- source/view/blocks.js
- source/view/index.js
-Adds in reflect and reflect_auto blocks
-Only propagates user-input values for non-auto blocks
-Fixes multiple-top-block counting in all cases
> Triangle Changes Addendum

- index.vwf.html
- source/view/missionBrief.css
- source/view/missionBriefs.js
@kadst43 
Forgot to do this before starting more complex things, but here it is. I moved it to mirror the blockly window. I had to remove some things like the banner image so it's extremely plain, but I can spice it up when we've settled on a home for the window. It's probably too tall, but I wanted to leave it the same size as the blockly window for review.
> Mission Brief Window

- source/rover.js
- source/scenario/mission4task2.vwf.yaml
- source/scene.js
- source/view/blocks.js
See commits :)
@kadst43 @BrettASwift
> SF punchlist 10-8 AM

- source/view/blocks.js
> Fix thisblock error

- index.vwf.html
- index.vwf.yaml
- source/rover.js
> Allow perry to interpolate, timer window, misplaced visibility

- source/view/blocks.js
Put checks for propagation in do-while to fix issue with multiple triangles.
> Multi-Triangle Fix

- index.vwf.yaml
- source/scenario/mission1task1.vwf.yaml
- source/scenario/mission1task2.vwf.yaml
- source/scenario/mission1task4.vwf.yaml
- source/scenario/mission2task7.vwf.yaml
- source/scene.js
- source/triggers/clauses/clause_DoOnce.js
- source/triggers/clauses/clause_DoOnce.vwf.yaml
@BrettASwift: Could you sanity check and make sure that there's not a better way for me to do this?
> - The DoOnce trigger is now reset when you start a new game.

- source/scenario/globalScenarioTriggers.vwf.yaml
- source/scenario/mission1task6.vwf.yaml
- source/scenario/mission4task1.vwf.yaml
- source/scenario/mission4task10.vwf.yaml
- source/scenario/mission4task11.vwf.yaml
- source/scenario/mission4task12.vwf.yaml
- source/scenario/mission4task13.vwf.yaml
- source/scenario/mission4task14.vwf.yaml
- source/scenario/mission4task15.vwf.yaml
- source/scenario/mission4task2.vwf.yaml
- source/scenario/mission4task3.vwf.yaml
- source/scenario/mission4task4.vwf.yaml
- source/scenario/mission4task5.vwf.yaml
- source/scenario/mission4task6.vwf.yaml
- source/scenario/mission4task7.vwf.yaml
- source/scenario/mission4task8.vwf.yaml
- source/scenario/mission4task9.vwf.yaml
- source/scenario/scenario.js
- source/scene.js
- source/triggers/actions/action_clearTriangle.js
@BrettASwift: For sanity check.  I'll finish cleaning up before I merge it.
> Move the clearing of scenario state into the scenario's start function, instead of doing it in the scene.js

- source/view/blocks.js
Set [] to ()
Vertically align coordinates
Resolve issue with error bubbles showing automatically (not able to have them automatically show yet - working on that fix)
Clear errors after block is deleted from workspace
MoveTo block now produces an error when not supplied component blocks
Limits bad block connectivity for transformation and flow blocks
> M4 Punchlist Items 10-13 AM

- source/view/blocks.js
> Comment block and procedure_def with top comment

- source/scenario/mission2task1.vwf.yaml
- source/scenario/mission3task1.vwf.yaml
- source/scenario/mission4task1.vwf.yaml
- source/triggers/actions/action_displayGraph.js
- source/triggers/actions/action_displayGraph.vwf.yaml
- source/triggers/actions/action_displayTiles.js
- source/triggers/actions/action_displayTiles.vwf.yaml
- source/triggers/generators/generator_Action.vwf.yaml
- M1: do nothing
- M2: toggle off tiles
- M3: toggle off both
- M4: toggle off tiles (only)
> Toggle the graph and/or tiles off at mission start:

- index.vwf.yaml
- source/scene.js
- source/shaders/texturedShader.vwf.yaml
> Tile Display on Ramp

- source/scene.js
- source/view/blocks.js
- source/view/index.js
See commits.
@kadst43 @BrettASwift
> 10-14 Punchlist

- index.vwf.html
- source/view/index.css
- source/view/index.js
- source/view/missionBrief.css
@kadst43 
- Moved mission brief next to rover element
- Added scrollbar to brief content
- Changed color of mission brief, comms, and tooltip background (the flat blue color didn't look good to me)
- Hide mission brief with rest of UI
- Added possible fix for blockly events being enabled when blockly is hidden (commented out until I can repro and test)
> Update mission brief layout and style

- source/view/missionBrief.css
- source/view/missionBriefs.js
@kadst43 
Closes the brief when clicking the hud icon if it is open
> Close brief when clicking hud icon

- source/view/index.js
> Fixed Blockly Node Selection

- source/view/index.js
@kadst43 
This should fix pointer events being enabled in blockly after running a program.
> Inherit pointer behavior in Blockly

- index.vwf.yaml
- source/shaders/mixMap.vwf.yaml
Rewrote the grid shader. The axis color should be more obvious now.
> Updated shader

- index.vwf.yaml
- source/scene.js
- source/shaders/mixMap.vwf.yaml
- source/view/blocks.js
- source/view/index.js
Okay, so... This is working. I had to strip it down to the bare minimum because nothing beyond that is working. The different triangle colors don't work for some reason. I have no clue why, so the user triangle color is hard-coded in the shader. I will keep hammering on it. If we have to draw multiple triangles in the same scenario, I will have to revisit and test that a lot. Please pull this and play through mission 4 with it. If you run into any problems, let me know. I'm not super confident that this is bug free (maybe that's just frustration from the parts I haven't gotten working yet, I don't know). I played through it and nothing broke, for what it's worth.
> Triangle shader revamp

- source/scenario/mission2task4.vwf.yaml
- source/view/blocks.js
Commits tell the story - changes how blocks flow values in the triangle missions if they aren't filled in.
> Triangle flow changes

- source/view/blocks.js
> Triangle flow changes fix

- source/marsGameSound.vwf.yaml
- source/scenario/mission2task11.vwf.yaml
- source/scenario/mission2task4.vwf.yaml
- source/scenario/mission2task9.vwf.yaml
> Mission 3 vo

- source/marsGameSound.vwf.yaml
- source/scenario/globalScenarioTriggers.vwf.yaml
- source/scenario/mission2task1.vwf.yaml
- source/scenario/mission2task10.vwf.yaml
- source/scenario/mission2task11.vwf.yaml
- source/scenario/mission2task2.vwf.yaml
- source/scenario/mission2task3.vwf.yaml
- source/scenario/mission2task4.vwf.yaml
- source/scenario/mission2task5.vwf.yaml
- source/scenario/mission2task6.vwf.yaml
- source/scenario/mission2task7.vwf.yaml
- source/scenario/mission2task8.vwf.yaml
- source/scenario/mission2task9.vwf.yaml
- source/triggers/clauses/clause_HasBlockWithFieldValue.js
- source/triggers/clauses/clause_HasBlockWithFieldValue.vwf.yaml
- source/triggers/generators/generator_Clause.vwf.yaml
> Block field clause

- source/fourWheeledRover.js
- source/rover.js
- source/view/blocklyUI.js
- source/view/index.js
@kadst43 
I didn't get the ground fit fixed and tested or the fix for the rover heading yet. This should eliminate any bugs caused by multiple clicks of the start/stop button and timing issues with that (there were a few perfect moments when you could run a program at the end of a scenario and succeed/fail). I also moved the dust, which is perhaps not necessary, but it's in there. I did at least remove one world transform retrieval that we weren't using, so it's doing it for 4 instead of 5.
> Bretts list

- source/view/index.js
Also made it so that the options menu closes when returning to the menu and cannot be opened from the menu.
> Escape Opens Options Menu

- index.vwf.yaml
- source/scenario/mission1successLinked.vwf.yaml
- source/scenario/mission2successLinked.vwf.yaml
Added chained success scenarios
> Add new scenarios that link the three success movies.

- source/scenario/mission2task11.vwf.yaml
- source/scene.js
@kadst43 
Also remove login success popup from this branch.
> Change M2 Success Linking

- index.vwf.html
- source/view/index.css
- source/view/index.js
@kadst43 
Seems to work fine for me. You might want to test and make sure it loads immediately for you, too.
> Loading Screen

- source/hud/batteryMeter.js
- source/hud/cameraSelector.js
- source/hud/firstPersonButton.js
- source/hud/thirdPersonButton.js
- source/hud/topDownButton.js
- source/rover.js
- source/scenario/scenario.js
- source/triggers/actions/action_buildBaseComponent.js
- source/triggers/actions/action_playSound.js
- source/triggers/actions/action_selectRover.js
- source/triggers/actions/action_stopAllSounds.js
- source/triggers/actions/action_stopSound.js
- source/triggers/actions/action_stopSoundGroup.js
- source/triggers/clauses/clause_BlocklyLineEval.js
- source/triggers/clauses/clause_OnSoundEnded.js
I replaced the obvious finds that were looking for nodes with known locations. There are still a lot of finds happening at startup it seems, but I wasn't able to eliminate those without a significant refactor. On my desktop, the load time went from 44 seconds total to 34 seconds total, so about a ~10 second difference.
> Optimize load
