virtual-world-framework/mars-game

index.vwf.yaml, source/hud/roverSelector.js, source/hud/roverSelector.vwf.yaml, source/scenario/scenario1a.vwf.yaml, source/scenario/scenario1b.vwf.yaml, source/scenario/scenario1c.vwf.yaml, source/scenario/scenario1d.vwf.yaml, source/scenario/scenario1e.vwf.yaml, source/scenario/scenario1f.vwf.yaml, source/scenario/scenario1g.vwf.yaml, source/scenario/scenario1h.vwf.yaml, source/scenario/scenario2a.vwf.yaml, source/scenario/scenario2b.vwf.yaml, source/scenario/scenario2c.vwf.yaml, source/scenario/scenario2d.vwf.yaml, source/scenario/scenario2e.vwf.yaml, source/scenario/scenario2f.vwf.yaml, source/scenario/scenario3a.vwf.yaml, source/scenario/scenario3b.vwf.yaml, source/scenario/scenario3c.vwf.yaml, source/scenario/scenario3d.vwf.yaml, source/scenario/scenario3e.vwf.yaml, source/scenario/scenario_dummy.vwf.yaml, source/scene.js, source/triggers/actions/action_enableBlocklyNodes.js, source/triggers/actions/action_enableBlocklyNodes.vwf.yaml, source/triggers/generators/generator_Action.vwf.yaml, source/view/index.js
- Changed `enableBlocklyTabs` to `enableBlocklyNodes` which enables the tabs and sets up the rover HUD icons.
- Improved enable/disable tabs by firing one event and passing an array of ids to the view, rather than firing an event for each tab.
- Improved the rover selector code by using only node IDs and removing rover node references.
Requires: https://github.com/virtual-world-framework/vwf/pull/482
=> Enable blockly nodes

source/view/blocklyUI.js, source/view/index.js
Rovers now work simultaneously, with some of Brett's suggestions incorporated to make the UI actually work with it.
=> Simultaneous Rover Programming

index.vwf.yaml, source/grid.js, source/grid.vwf.yaml, source/rover.js, source/triggers/actions/action_removeFromGrid.js
- Fixed the bug with rovers not updating their locations on the grid properly, causing collisions where the rover used to be.
- Modified some grid methods to use node IDs instead of nodes.
- Tiles now store node IDs rather than node references in their objects arrays.
- This eliminates most of the `valueJSFromKernel` warnings.
=> Fix Grid Collision

source/triggers/groups/triggerGroup.js
Saves maybe 2-3% of execution time, so not huge.
@BrettASwift
=> Remove VWF calls from the inner loop of trigger group checks.  

source/view/index.js
This is one of those really odd bugs that stresses the importance of making sure there are no errors in the console. The tiles not blinking were caused by an error being generated when `pov` was undefined in the `mountName` `satProperty` handler. This caused `mountName` to no longer be able to be set in the model, so it was stuck with a value of `default` after the camera pans to the radio. The tile blinking checks to make sure that the value of `mountName` is `topDown` or else it does not blink.
=> Fix Tile Blinking

source/scenario/scenario1b.vwf.yaml, source/scenario/scenario_dummy.vwf.yaml, source/view/videoController.js
Modified `videoController.js` to support the changes made in [#489](https://github.com/virtual-world-framework/vwf/pull/489). Also added (commented out) code in `scenario_dummy` for testing of the preloading functionality. 
Depends on [#489](https://github.com/virtual-world-framework/vwf/pull/489).
=> Jplayer preload

index.vwf.yaml, source/callouttile.js, source/cameraMount.vwf.yaml, source/cameraTarget.js, source/cinematicCameraController.js, source/gameCamera.js, source/gameCamera.vwf.yaml, source/scenario/scenario1a.vwf.yaml, source/scenario/scenario1b.vwf.yaml, source/scenario/scenario1c.vwf.yaml, source/scenario/scenario1d.vwf.yaml, source/scenario/scenario1e.vwf.yaml, source/scenario/scenario1f.vwf.yaml, source/scenario/scenario1g.vwf.yaml, source/scenario/scenario1h.vwf.yaml, source/scenario/scenario_dummy.vwf.yaml, source/scene.js, source/view/navigation.js
These are the changes for camera collisions and the less strictly controlled third person camera. These changes do not include checking for camera collisions as the camera target is moving and camera itself is stationary. My solution for that caused some fighting between the view and model. I still need to find a better place to put that.
What is included:
- Removed camera snapping when running blockly
- Remember last camera pose in third person
- Push camera inward when colliding with world
- Collides when user input is moving the camera
- Collides when camera mode is initially set (when switching targets or view modes)
@kadst43 @AmbientOSX
=> Camera Changes

source/shaders/projectedGrid.vwf.yaml, source/shaders/texturedShader.vwf.yaml
Here's a basic version of the projected grid shader. I don't have an example in mars-game yet, but I do have a screenshot from a test application:
This is the mix map shader + the projected grid. There are several uniforms that affect the appearance of the grid (color, thickness, etc). I'm still modifying how these uniforms behave, so this isn't done yet. I just wanted to get a preview up.
=> Projected grid shader

source/grid.js, source/scenario/blockly/scenario2a.xml, source/scenario/blockly/scenario2b.xml, source/scenario/blockly/scenario2c.xml, source/scenario/blockly/scenario2d.xml, source/scenario/blockly/scenario2e.xml, source/view/index.js
Fixes for Blockly bugs in scenario 2 and a fix for checking `surroundingTiles`. Sometimes it was `null` and `null !== undefined` is true. Converted to a boolean to make the check more robust.
=> Misc bug fixes

source/view/index.css
Updated the tooltip window to look more like the logger box. Changed height restriction so that smaller tips have less negative space.
@kadst43 @AmbientOSX @jyucra
=> Update tooltips to match UI.

source/view/tooltips.js
Makes the tooltips disappear when the mouse hovers out of a specific blocks instead of disappearing whenever a mousemove event is triggered.
=> Further tooltip changes

source/scenario/blockly/mission4_perry.xml, source/scenario/blockly/scenario1g.xml, source/scenario/blockly/scenario1h.xml, source/scenario/blockly/scenario2f.xml, source/scenario/blockly/scenario3a.xml, source/scenario/blockly/scenario3b.xml, source/scenario/blockly/scenario3c.xml, source/scenario/blockly/scenario3d.xml, source/scenario/blockly/scenario3e.xml, source/scenario/blockly/scenario_dummy.xml, source/scenario/blockly/scenario_dummy_perry.xml
Changed createTriangle and the forLoop block so that they have pre-built inputs set to 0 even while in the toolbox. This cuts down on the number of blocks you have to drag over.
=> Nested Blockly Toolbox

index.vwf.yaml
Made the grid lines thinner and less intense so the red and blue lines are more apparent. Also changed the normal grid lines to be closer to white where they were gold/yellow.
=> Grid Visual Tweaks

index.vwf.yaml, source/cinematicCameraController.js
I didn't think this would take so long to figure out, but this should do the trick. When panning to the node, we're copying the camera's current pose and world offset so no matter what mode/rotation is on the camera, it will be preserved.
=> Camera Pan Fix

index.vwf.yaml, source/scene.js, source/view/index.js, source/view/navigation.js
@kadst43 @AmbientOSX @jyucra 
- Toggling on the graph now snaps to top down view
- Third person minimum zoom is based on `roverRadius` property of rover
- Added `worldOffset` to third person camera mounts so that the camera is pointed toward the middle of the rover, rather than the ground ( the rover's origin )
=> Camera updates

source/hud/marsGameHud.js, source/hud/marsGameHud.vwf.yaml, source/scenario/newmission3task1.vwf.yaml, source/scenario/newmission3task2.vwf.yaml, source/scenario/newmission3task3.vwf.yaml, source/scenario/newmission3task4.vwf.yaml, source/scenario/newmission3task5.vwf.yaml, source/scenario/newmission3task6.vwf.yaml, source/scenario/newmission3task7.vwf.yaml
Unfortunately, I couldn't get the performance good enough for graying out the HUD. I tried everything I could think of to optimize it, but rendering it using the HTML Canvas every frame was just too slow. I had to fall back to using the same disable we use on the individual elements and just change the alpha if the entire hud is disabled.
Requires: https://github.com/virtual-world-framework/vwf/pull/509
=> Disable hud

source/hud/blocklyButton.js, source/hud/firstPersonButton.js, source/hud/graphButton.js, source/hud/marsGameHud.vwf.yaml, source/hud/missionButton.js, source/hud/optionsButton.js, source/hud/thirdPersonButton.js, source/hud/tilesButton.js, source/hud/topDownButton.js
I finally got the bug to occur and promptly dug into the objects to find that the automatic draw order of the HUD was failing us. We have the battery element listed in `marsGameHud.vwf` first so that it will be the first object created. We do this because it has some draw commands that work as a mask. Drawing it after the other elements would cause them to disappear. It turns out that some times the battery element doesn't get created quick enough by VWF and the next elements in the list jump ahead, causing their draw order to be before the battery element's mask. So, to remedy this, I've made it possible to explicitly set the draw order of the HUD elements and added their draw orders to the `marsGameHud.vwf` file.
Requires: …
=> hud-draw-order

source/rover.js, source/view/index.js
We disabled doing things this way because we thought it might be contributing to the wandering issue. That doesn't seem to be a problem anymore and the alternative way I was trying to fix/refactor this code was plagued by timing issues and cache issues. Lets do it this way for now since it is tried and true. I will revisit my refactor if I have time later next week.
=> Perry Movement Speed

source/hud/marsGameHud.js, source/hud/marsGameHud.vwf.yaml
This now hides all of the HUD elements apart from the comms portraits at the beginning of missions.
=> Hide HUD During Instructional Dialog

source/view/index.js
Reopens the blockly tab when the scenario reloads the toolbox XML and adds a safety check for a Blockly node being present. I realize it would be nice to keep it open but Blockly recreates the toolbox tree when it loads new toolbox XML. I will look into changing this in the core.
@kadst43
=> Reopen Blockly Category

index.vwf.yaml, source/scenario/introCinematic.vwf.yaml, source/scenario/mission1success.vwf.yaml, source/scenario/mission2success.vwf.yaml, source/scenario/mission3success.vwf.yaml, source/scene.js, source/view/index.js, source/view/mainMenu.js
Using David's change to suspend rendering, this stops rendering when each of the videos are playing. The increased performance also exacerbated the issue with the scene showing up before the intro video plays. I tried fixing it and only saw a very small improvement. However, the changes I made were good changes, so I left them in. I still am trying to find a way to solve that problem.
Let me know if the video performance is better now that rendering is suspended. Remember to update to the latest vwf/mars-game-development before testing.
=> Suspend Renderer During Videos

source/scenario/mission4task1.vwf.yaml, source/scenario/mission4task2.vwf.yaml, source/scenario/mission4task3.vwf.yaml, source/scenario/mission4task4.vwf.yaml, source/scenario/mission4task5.vwf.yaml, source/scenario/mission4task6.vwf.yaml, source/scene.js, source/shaders/mixMap.vwf.yaml, source/triggers/actions/action_clearTriangle.js, source/triggers/actions/action_clearTriangle.vwf.yaml, source/triggers/generators/generator_Action.vwf.yaml
This allows up to 4 triangles to be drawn by the shader. In order to pass them in, you'll just have to add 3 more points to the `material.triangle` property.
`material.triangle = [ pa, pb, pc, pd, pe, pf ]` Would be 2 triangles, where pa, pb, and pc are the points of the first and pd, pe, and pf are the points of the second. Each point is of the format `[ x, y ]`. Anything beyond the 12th point will not be rendered by the shader.
I can go ahead and make changes to the code to make adding/managing points easier if you'd like. If so, I will wait until that is done before merging this.
=> Four Triangle Shader

source/scenario/mission4task1.vwf.yaml, source/scenario/mission4task10.vwf.yaml, source/scenario/mission4task11.vwf.yaml, source/scenario/mission4task12.vwf.yaml, source/scenario/mission4task13.vwf.yaml, source/scenario/mission4task14.vwf.yaml, source/scenario/mission4task15.vwf.yaml, source/scenario/mission4task2.vwf.yaml, source/scenario/mission4task3.vwf.yaml, source/scenario/mission4task4.vwf.yaml, source/scenario/mission4task5.vwf.yaml, source/scenario/mission4task6.vwf.yaml, source/scenario/mission4task7.vwf.yaml, source/scenario/mission4task8.vwf.yaml, source/scenario/mission4task9.vwf.yaml, source/scene.js, source/shaders/mixMap.vwf.yaml, source/triggers/actions/action_setConstructed.js, source/triggers/actions/action_setConstructed.vwf.yaml, source/triggers/generators/generator_Action.vwf.yaml, source/view/missionBrief.css
@kadst43 @AmbientOSX @jyucra 
- Made the mission brief window shorter for smaller resolution screens. The contents now have the ability to scroll.
- Fixed a console warning caused by the rover facing arrow changes.
- Added `setConstructed` action for immediately setting base components to constructed or hidden.
- Modified Mission 4 to use `setConstructed` action to fix objects that should be built not appearing.
- Fixed bug where blinking tiles would stay lit up after scenario changed.
- Fixed bug where highlighted tiles and triangles would stay visible when switching to a scenario without them.
=> Brett's Punchlist

source/gameCamera.js
@kadst43 @AmbientOSX @eric79 
So, it turns out that if you use the `transformTo` method without a duration, the threejs view driver skips interpolation of that transform. I opted to go with setting the property rather than adding a duration, since the duration can cause repeated transforms to get jammed up if it is too long and look jumpy if it's too short. This fixes the camera jitter when following the target node, however, if the app is running slowly, you'll notice some lag/fighting when controlling the camera while it is following the target node.
=> Fix Camera Jitter

index.vwf.yaml, source/scene.js, source/triggers/actions/action_setThirdPersonStartPose.js, source/view/index.js
@kadst43 
I left the change to that action in there. Haven't determined if it is obsolete yet.
Edit: `readCameraPose()` will display the current pose in `[ radius, yaw, pitch ]` and `writeCameraPose( radius, yaw, pitch )` can be used to set the camera pose (you can also move it with the mouse, of course, but this way you can test cleaner numbers).
=> Fix action + add view functions for camera setting

source/scenario/mission2task10.vwf.yaml, source/scenario/mission2task2.vwf.yaml, source/scenario/mission2task3.vwf.yaml, source/scenario/mission2task8.vwf.yaml, source/view/blocks.js, source/view/index.js
@BrettASwift @kadst43 
Commits should be somewhat explanatory but will give a rundown.
-Disabled tab for the browser window to avoid the reloading issue.
-y= is now movable but not deletable for M2
-The triangle_flow and transformation blocks will show the right A'B'C' "prime" count depending on which transformation it is.
-Warnings are now split up on multiple lines
-If block should now accept a wider variety of inputs
-Critically for triangle vis: if the block is in the flyout it will not send its ID or vertices over to the view for visualization.
Let me know if there are any questions.
=> Punchlist and Triangle Vis Support

source/scenario/mission2task2.vwf.yaml
I didn't dig into this one. On a hunch, I assumed the way we're defining what tabs we use in the scenarios now is clearing the tabs and the blinking after we tell it to make the tab blink, so I moved the blink call to after the blockly window is opened. I tested it and it worked, but I cannot verify that my hunch is correct, only that this solution worked. Hope that's good enough for now. If not, I will dig into it further.
=> Fix for blinking tab in mission 2 task 2

source/hud/marsGameHud.vwf.yaml, source/rover.js
Removed the alerts for low memory/power and blocked. None of them are very visible and the ones that are, just confuse the player. Up to you if you want to merge it. It's minor.
=> Remove rover alerts

source/hud/marsGameHud.vwf.yaml, source/rover.js, source/view/navigation.js
Remove alerts and extend helicam radius so that you can pan to see the radio at the default zoom level.
=> No alerts + helicam radius

index.vwf.html, source/view/index.css, source/view/index.js
This should remove the scene flashing at the start of the game. It also causes us to immediately cut to videos, though. So the 400ms fade in doesn't happen. I don't think it looks bad. Definitely the benefit outweighs the cost.
=> Remove scene flash
